version: "3.9"

services:
    app:
        build:
            context: ./app
        command: bash -c "cd app && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=${BACKEND_HOST}:${BACKEND_PORT}"
        restart: always
        volumes:
            - ./app/templates:/usr/src/code/app/templates
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        env_file:
            - .env
